{
 "title": "test",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU load percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU load average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPULA 1" },
    { "expr": "node_load5", "legendFormat": "CPULA 5" },
    { "expr": "node_load15", "legendFormat": "CPULA 15" }
   ]
  },
  {
   "title": "Memory free",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "Disk free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_filesystem_free_bytes" }
   ]
  }
 ]
}